### ISSUE TITLE
Exception when parsing "4 0 L/2 2 0"

### ISSUE THREAD

**Issue by cuu508** [pallets-eco/croniter#34]
To reproduce:

```python
>>> from datetime import datetime
>>> from croniter import croniter
>>> croniter("4 0 L/2 2 0", datetime.now())
Traceback (most recent call last):
  File "/home/user/venvs/croniter-fuzzing/lib/python3.10/site-packages/croniter/croniter.py", line 778, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/user/venvs/croniter-fuzzing/lib/python3.10/site-packages/croniter/croniter.py", line 691, in _expand
    not low or not high or int(low) > int(high)
ValueError: invalid literal for int() with base 10: 'l'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/venvs/croniter-fuzzing/lib/python3.10/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/user/venvs/croniter-fuzzing/lib/python3.10/site-packages/croniter/croniter.py", line 785, in expand
    exec("raise CroniterBadCronError from  exc", globs, locs)
  File "<string>", line 1, in <module>
NameError: name 'exc' is not defined. Did you mean: 'exec'?
```

**Comment by kiorky** [comment]
fixed in 1.3.10
