### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by tombeteende** [pallets-eco/croniter#59]
I run the folllowing code and get an error - 

```
from croniter import croniter

import datetime

date = datetime.datetime.now() + datetime.timedelta(days=1)
cron_expression =  "* * * * *"
cron = croniter(cron_expression, date)

next = cron.get_next(datetime)

print(next)
``` 

Error -

```
Traceback (most recent call last):
  File "minimal_example.py", line 9, in <module>
    next = cron.get_next(datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<***>python3.12/site-packages/croniter/croniter.py", line 201, in get_next
    return self._get_next(ret_type or self._ret_type, is_prev=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<***>/python3.12/site-packages/croniter/croniter.py", line 260, in _get_next
    if not issubclass(ret_type, (float, datetime.datetime)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

I believe it relates to python version update since it used to work on 3.11

Python version - Python 3.12.1
croniter version - 2.0.1

**Comment by kiorky** [comment]
I do not reproduce with python 3.12.1

**Comment by kiorky** [comment]
You code has a problem, it should be 

```py
next = cron.get_next(datetime.datetime)
```
